# Register new user
POST https://notes-server-xkt1.onrender.com/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Sonu",
    "email": "sonu2@test.com",
    "password": "sonu123"
}

###

# Login to existing
POST https://notes-server-xkt1.onrender.com/auth/login HTTP/1.1
content-type: application/json

{
    "email": "sonu@test.com",
    "password": "sonu123"
}

###

# Update user profile
PUT https://notes-server-xkt1.onrender.com/user/633c8cfe3980a0303cd9e749 HTTP/1.1
Content-Type: application/json

{
    "password": "sonu123"
}

###

# Delete user profile
DELETE https://notes-server-xkt1.onrender.com/user/633c8cfe3980a0303cd9e749 HTTP/1.1
Content-Type: application/json

###

# Get user profile
GET https://notes-server-xkt1.onrender.com/user HTTP/1.1
Content-Type: application/json

###

# Add new notes
POST https://notes-server-xkt1.onrender.com/notes/ HTTP/1.1
Content-Type: application/json

{
    "title": "My demo notes",
    "content": "This is a demo note",
    "tags": "demo,first"
}

###

# Get notes
GET https://notes-server-xkt1.onrender.com/notes/633c8ec36455d43498de09fb HTTP/1.1
Content-Type: application/json

###

# Get notes by query
GET https://notes-server-xkt1.onrender.com/notes/search?q=demo HTTP/1.1
Content-Type: application/json

###

# Get notes by query
GET https://notes-server-xkt1.onrender.com/notes/all HTTP/1.1
Content-Type: application/json