# Register new user
POST http://localhost:3333/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Sonu",
    "email": "sonu2@test.com",
    "password": "sonu123"
}

###

# Login to existing
POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

{
    "email": "sonu@test.com",
    "password": "sonu123"
}

###

# Update user profile
PUT http://localhost:3333/user/633c8cfe3980a0303cd9e749 HTTP/1.1
Content-Type: application/json

{
    "password": "sonu123"
}

###

# Delete user profile
DELETE http://localhost:3333/user/633c8cfe3980a0303cd9e749 HTTP/1.1
Content-Type: application/json

###

# Get user profile
GET http://localhost:3333/user HTTP/1.1
Content-Type: application/json

###

# Add new notes
POST http://localhost:3333/notes/ HTTP/1.1
Content-Type: application/json

{
    "title": "My demo notes",
    "content": "This is a demo note",
    "tags": "demo,first"
}

###

# Get notes
GET http://localhost:3333/notes/633c8ec36455d43498de09fb HTTP/1.1
Content-Type: application/json

###

# Get notes by query
GET http://localhost:3333/notes/search?q=demo HTTP/1.1
Content-Type: application/json

###

# Get notes by query
GET http://localhost:3333/notes/all HTTP/1.1
Content-Type: application/json